task default: [:play]

desc 'executa suite de testes usando `rspec` com formatacao de documento'
task :test do
  system 'rspec -f d'
end

desc 'executa apenas a app'
task :play do
  system 'ruby main.rb'
end
